name: 'Terraform GitHub Actions'
on:
  - push

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Format '
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.4
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./_example"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

      - name: Configure AWS Credentials
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.4
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./_example"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Init redis-cluster'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.4
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./_example/redis-cluster"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Init redis'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.4
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./_example/redis"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'Clouddrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()